services:
  database:
    image: 'postgres:16-alpine'
    ports:
      - '5432'
    environment:
      - 'POSTGRES_DB=testDatabase'
      - 'POSTGRES_USER=testUser'
      - 'POSTGRES_PASSWORD=testPassword'